### ISSUE TITLE
KG completion

### ISSUE THREAD

**Issue by giacoballoccu** [johnnyjana730/UCPR#1]
Hi!

Congrats on the great work with UCPR. Was looking for ML1M KG completion since you're of the few to use the Satori completion as it seems to be of higher quality compared to the one obtained from DBpedia.

I wanted to know if you can make available the whole completion including the relation_list file that maps the number [0,12] to the original relation in the KG since is something very important for producing explainable paths. Also, I find missing the mappings between the original dataset and the entities in the KG. 

Additionally wanted to know why the dataset has only 753775 interactions instead of 1M given that ML1M has already all users with >20 interactions so your alpha-core setting shouldn't have affected the number of interactions.

**Comment by johnnyjana730** [comment]
For ML1M, this dataset is first proposed by Wang et, al (https://github.com/hwwang55/RippleNet). To my best knowledge, they don't release the original entity information although I have asked them to provide it. Still,  some information is missing like the entity mapping for ML1M. so it still misses a lot of information if I don't convert it to a numeric one.

For the dataset statistic issue, I suggest you preprocess the ML1M data by yourself. I provide the preprocess code too.
